remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Coder7 - Pages
author: Bradley Hook, gh:bradley-coder7, bradley@coder7.com
description: A collection of projects and notes to be shared with the world 
